### ISSUE TITLE
Ticket #8914 - status

### ISSUE THREAD

**Issue by joycemccoy** [RVSchools/buildouts#1]
Service Request #8,914 has been modified

> Title: Corporate Website
> Description: From the View tab the State dropdown arrow is not displaying on Pages, Files, and Links, so the State cannot be changed from View. Collections, Folders, and Images do display the dropdown arrow and the state can be changed from the View Tab. We would like Pages Files and LDInks to work the same way, and apparently they used to. 
> Can this functionality be added back in for these items?
> Category: Plone
> Sub Category: Content
> Location: Education Centre
> Assigned To: none
> Priority: Normal
> Urgency: Normal
> Status: Open
> Request User: abergshoeff
> Notes: Angela Bergshoeff (11/26/14 2:06 PM): 
> # Any word on this one? Maybe Carlos could take a look at this as well.
> 
> Angela Bergshoeff (11/13/14 3:45 PM): 
> Also under Actions, there is no delete option on any content item. The only option is now copy.
> Total Active Requests: 359
> Active requests for none: 9

**Comment by joycemccoy** [comment]
8914: Corporate Website: From the View tab the State dropdown arrow is not displaying on Pages, Files, and Links, so the State cannot be changed from View. Collections, Folders, and Images do display the dropdown arrow and the state can be changed from the View Tab.  We would like Pages Files and
LDInks to work the same way, and apparently they used to.  Can this functionality be added back in for these items? Also under Actions, there is no delete option on any content item.  The only option is now copy.

**Comment by cguardia** [comment]
This is working on the site now. For example, see: http://www.rockyview.ab.ca/staff/generalstore
