### ISSUE TITLE
Ticket 8987

### ISSUE THREAD

**Issue by joycemccoy** [RVSchools/buildouts#2]
Hi Carlos 
Here is an issue that Angela is having with the school sites. Can you have a look at it? When you resolve it, I can replicate the fix site by site if you need. There are a few more issues I'll send today. 

Thanks! 

J

> New Service Request #8,987
> 
> Title: Links in Portlets on School Sites not opening in new window
> Description: On all of our school sites, the links that appear in portlets are not opening in a new window. I am not sure why, I am pretty sure this was working before.
> 
> Here are a few examples:
> 
> http://eastlake.rockyview.ab.ca/parents (all of the links in navigation overwrite the site even though they are external). 
> http://nosecreek.rockyview.ab.ca/parents 
> 
> External links that appear on a page work properly.
> 
> This is happening on all sites.
> Category: Plone
> Sub Category: Content
> Location: Education Centre
> Assigned To: none
> Priority: Normal
> Urgency: Normal
> Status: New
> Request User: abergshoeff
> Total Active Requests: 359
> Active requests for none: 9

**Comment by joycemccoy** [comment]
There seem to be quite a few errors reported, and quite often when adding

> > > in an item, the site gives an error, page can not be found, but when the
> > > screen is refreshed the item is there.
> > > http://springmd.rockyview.ab.ca/prefs_error_log_form Elbow Valley also
> > > has quite a few errors.
> > > http://evalley.rockyview.ab.ca/prefs_error_log_form 
> > > (Internal 8728) I have tested school and corporate site and found that
> > > even when you are not logged in, when you click on a PDF you are asked to
> > > click on it a second time (another Plone window opens) to open it.
> > > http://cochrane.rockyview.ab.ca/parents/school-supplies for example. There
> > > should be no secondary window pop up when you click on the PDF- it should
> > > either open or present a download/open screen, not another Plone screen
> > > asking you to click it again.
> > > (Internal 8914)On www.rockyview.ab.ca From the View tab the State
> > > dropdown arrow is not displaying on Pages, Files, and Links, so the State
> > > cannot be changed from View. Collections, Folders, and Images do display the
> > > dropdown arrow and the state can be changed from the View Tab. We would like
> > > Pages Files and LDInks to work the same way, and apparently they used to.
> > > Can this functionality be added back in for these items? Also under Actions,
> > > there is no delete option on any content item. The only option is now copy.
> > > (Internal 8987) On all of our school sites, the links that appear in
> > > portlets are not opening in a new window. I am not sure why, I am pretty
> > > sure this was working before. Here are a few examples:
> > > http://eastlake.rockyview.ab.ca/parents (all of the links in navigation
> > > overwrite the site even though they are external).
> > > http://nosecreek.rockyview.ab.ca/parents External links that appear on a
> > > page work properly. This is happening on all sites.

**Comment by cguardia** [comment]
The links are working properly now.
